version: '2'
services:
 web:
  build: .
  ports:
    - "5000:5000"
  container_name: hospital-soap
  image: hospital:v2
 app:
   build: ./UsersPostsComments/Service
   image: tautvis/service
   working_dir: /Service
   volumes:
    - ./UsersPostsComments/Service:/Service
    - ~/.m2:/root/.m2
   ports:
    - "80:80"
   command: mvn clean spring-boot:run
   container_name: userspostscomments_app_1
   depends_on:
    - mysql2
   links:
    - mysql2
 mysql2:
   image: mysql:5.7
   ports:
    - "3306:3306"
   environment:
    MYSQL_DATABASE: WebServicesPostsService
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   container_name: mysql-standalone
   volumes:
    - ./UsersPostsComments/init.sql:/docker-entrypoint-initdb.d/init.sql
