//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 09:37:48 PM EEST 
//


package com.hospital.doctors;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hospital.doctors package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hospital.doctors
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllDoctorRequest }
     * 
     */
    public GetAllDoctorRequest createGetAllDoctorRequest() {
        return new GetAllDoctorRequest();
    }

    /**
     * Create an instance of {@link DeleteDoctorRequest }
     * 
     */
    public DeleteDoctorRequest createDeleteDoctorRequest() {
        return new DeleteDoctorRequest();
    }

    /**
     * Create an instance of {@link UpdateDoctorRequest }
     * 
     */
    public UpdateDoctorRequest createUpdateDoctorRequest() {
        return new UpdateDoctorRequest();
    }

    /**
     * Create an instance of {@link CreateDoctorRequest }
     * 
     */
    public CreateDoctorRequest createCreateDoctorRequest() {
        return new CreateDoctorRequest();
    }

    /**
     * Create an instance of {@link RegisterDoctorAsUserRequest }
     * 
     */
    public RegisterDoctorAsUserRequest createRegisterDoctorAsUserRequest() {
        return new RegisterDoctorAsUserRequest();
    }

    /**
     * Create an instance of {@link CreateDoctorResponse }
     * 
     */
    public CreateDoctorResponse createCreateDoctorResponse() {
        return new CreateDoctorResponse();
    }

    /**
     * Create an instance of {@link Doctor }
     * 
     */
    public Doctor createDoctor() {
        return new Doctor();
    }

    /**
     * Create an instance of {@link CreatePostForDoctorRequest }
     * 
     */
    public CreatePostForDoctorRequest createCreatePostForDoctorRequest() {
        return new CreatePostForDoctorRequest();
    }

    /**
     * Create an instance of {@link CreateCommentForDoctorResponse }
     * 
     */
    public CreateCommentForDoctorResponse createCreateCommentForDoctorResponse() {
        return new CreateCommentForDoctorResponse();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link DeleteDoctorResponse }
     * 
     */
    public DeleteDoctorResponse createDeleteDoctorResponse() {
        return new DeleteDoctorResponse();
    }

    /**
     * Create an instance of {@link CreateCommentForDoctorRequest }
     * 
     */
    public CreateCommentForDoctorRequest createCreateCommentForDoctorRequest() {
        return new CreateCommentForDoctorRequest();
    }

    /**
     * Create an instance of {@link GetDoctorResponse }
     * 
     */
    public GetDoctorResponse createGetDoctorResponse() {
        return new GetDoctorResponse();
    }

    /**
     * Create an instance of {@link GetAllDoctorResponse }
     * 
     */
    public GetAllDoctorResponse createGetAllDoctorResponse() {
        return new GetAllDoctorResponse();
    }

    /**
     * Create an instance of {@link RegisterDoctorAsUserResponse }
     * 
     */
    public RegisterDoctorAsUserResponse createRegisterDoctorAsUserResponse() {
        return new RegisterDoctorAsUserResponse();
    }

    /**
     * Create an instance of {@link CreatePostForDoctorResponse }
     * 
     */
    public CreatePostForDoctorResponse createCreatePostForDoctorResponse() {
        return new CreatePostForDoctorResponse();
    }

    /**
     * Create an instance of {@link Post }
     * 
     */
    public Post createPost() {
        return new Post();
    }

    /**
     * Create an instance of {@link GetDoctorRequest }
     * 
     */
    public GetDoctorRequest createGetDoctorRequest() {
        return new GetDoctorRequest();
    }

    /**
     * Create an instance of {@link UpdateDoctorResponse }
     * 
     */
    public UpdateDoctorResponse createUpdateDoctorResponse() {
        return new UpdateDoctorResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

}
