//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 04:46:01 PM EEST 
//


package com.hospital.doctors;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hospital.doctors package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hospital.doctors
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateDoctorRequest }
     * 
     */
    public CreateDoctorRequest createCreateDoctorRequest() {
        return new CreateDoctorRequest();
    }

    /**
     * Create an instance of {@link CreateDoctorResponse }
     * 
     */
    public CreateDoctorResponse createCreateDoctorResponse() {
        return new CreateDoctorResponse();
    }

    /**
     * Create an instance of {@link Doctor }
     * 
     */
    public Doctor createDoctor() {
        return new Doctor();
    }

    /**
     * Create an instance of {@link GetDoctorResponse }
     * 
     */
    public GetDoctorResponse createGetDoctorResponse() {
        return new GetDoctorResponse();
    }

    /**
     * Create an instance of {@link GetDoctorRequest }
     * 
     */
    public GetDoctorRequest createGetDoctorRequest() {
        return new GetDoctorRequest();
    }

}
